# https://pre-commit.com/hooks.html

default_language_version:
  python: "python3.10"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--config-file=pyproject.toml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--rcfile=pyproject.toml"]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: ["--config=pyproject.toml"]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--settings-file=pyproject.toml"]
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        args: ["--config=pyproject.toml"]
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
        args: ["-c pyproject.toml"]
      - id: vulture
        name: vulture
        entry: vulture
        language: system
        types: [python]
