signature_template: "\n\n<FuncSignature>\n<pre>\n{signature}\n</pre>\n</FuncSignature>\n\n"
heading_template: "\n\n<FuncHeading>{heading}</FuncHeading>\n\n"
param_template: "\n\n<FuncElement name='{name}' type='{type}'>\n\n{description}\n\n</FuncElement>\n\n"
return_template: "\n\n<FuncElement name='{name}'>\n\n{description}\n\n</FuncElement>\n\n"
module_map:
  cityseer.tools.plot: docs/tools/plot.md
  cityseer.tools.graphs: docs/tools/graphs.md
  cityseer.tools.mock: docs/tools/mock.md
  cityseer.metrics.networks: docs/metrics/networks.md
  cityseer.metrics.layers: docs/metrics/layers.md
