package_root_relative_path: '.'
intro_template: "
  ---\n
  import { Markdown } from 'astro/components';\n
  import ArXivLink from '@src/components/ArXivLink.vue'\n
  import PageLayout from '@src/layouts/PageLayout.astro'\n
  ---\n
  \n
  <PageLayout>
  "
outro_template: "\n
  </PageLayout>\n
  "
module_map:
  cityseer.metrics.layers:
    py: ./cityseer/metrics/layers.py
    astro: ./docs/src/pages/metrics/layers.astro
  cityseer.metrics.networks:
    py: ./cityseer/metrics/networks.py
    astro: ./docs/src/pages/metrics/networks.astro
  cityseer.tools.graphs:
    py: ./cityseer/tools/graphs.py
    astro: ./docs/src/pages/tools/graphs.astro
  cityseer.tools.mock:
    py: ./cityseer/tools/mock.py
    astro: ./docs/src/pages/tools/mock.astro
  cityseer.tools.plot:
    py: ./cityseer/tools/plot.py
    astro: ./docs/src/pages/tools/plot.astro
